spring:
  profiles:
    active: local # 기본 환경 선택
  jackson:
    serialization:
      fail-on-empty-beans: false
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

# local 환경
---
spring:profiles: local
spring.profiles.include: real-db

server:
  ssl:
    enabled: true
    key-store: classpath:oms_keystore
    key-store-password: oms20190131
    key-alias: alias
    enabled-Protocols: TLSv1.2
  port: 3000
  error:
    whitelabel:
      enabled: false

# MARIA DB
---
spring:
  profiles: real-db
  datasource:

    url: jdbc:mariadb://localhost:3306/pc_protector?allowMultiQueries=true
    username: pcprotector
    password: asdasd
    driver-class-name: org.mariadb.jdbc.Driver

# MYBATIS
---
mybatis:
  type-aliases-package: oms.pc_protector.restApi.result.model
  configuration:
    map-underscore-to-camel-case: true

# File Upload Size
---
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 4MB
      enabled: true